# Generated by Django 3.0.5 on 2020-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default=None, max_length=200, verbose_name='Text Title'),
            preserve_default=False,
        ),
    ]
