# Generated by Django 3.0.5 on 2020-04-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_text_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='sentences.Text'),
        ),
    ]
