# Generated by Django 3.0.5 on 2020-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0003_auto_20200428_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='nlp_doc_bytes',
            field=models.BinaryField(default=None, max_length=65536, verbose_name='Sentence NLP data dump'),
            preserve_default=False,
        ),
    ]
